### ISSUE TITLE
Comfortable feature

### ISSUE THREAD

**Issue by Eiphoria** [qerdcv/ttt-online#39]
After click "Play" button and then button "Load game", appear popup window where you should type "Game ID:". After this window appear input field should be on focus. This mean that you don`t need select input field manually.
Practical behavior - input field isn't active after window appear:
![image](https://user-images.githubusercontent.com/71280626/181281532-a0602be9-a97e-4d58-ae8a-64db4002c85f.png)
Expected behavior - input field is active after window appear:
![image](https://user-images.githubusercontent.com/71280626/181282610-93e11cd5-c20c-43bb-9e0f-ea5e79482ec6.png)

**Comment by qerdcv** [comment]
Done!
You can check this out on https://ttto.qerdcv.com
